apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: awx-telegram-webhook
  namespace: awx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    # nginx.ingress.kubernetes.io/backend-protocol: "HTTP"  
spec:
  ingressClassName: nginx
  tls:  
  - hosts:
    - webhook.example.com
    secretName: webhook-tawx-tls  
  rules:
  - host: weebhook.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: awx-telegram-webhook
            port:
              number: 80
